FROM registry.cn-beijing.aliyuncs.com/songjinghe/ubuntu-oraclejdk-maven:2019-12-16-10-18-20
MAINTAINER Jinghe Song <songjh@act.buaa.edu.cn>

RUN echo $PWD
VOLUME /root/.m2
ENV MAVEN_OPTS '-Xmx512m'

RUN mkdir -p /tmp/build
WORKDIR /tmp/build

# 构建TGraph
RUN git clone --depth=1 https://github.com/TGraphDB/temporal-storage.git -b TGraph2.3latest --single-branch
RUN git clone --depth=1 https://github.com/TGraphDB/temporal-neo4j.git -b TGraph2.3latest --single-branch
RUN git clone --depth=1 https://github.com/TGraphDB/TGraph-demo-test.git -b master --single-branch

WORKDIR /tmp/build/temporal-storage
RUN mvn -B install -Dmaven.test.skip=true

WORKDIR /tmp/build/temporal-neo4j
RUN mvn -B install -DskipTests -Dlicense.skip=true -Dlicensing.skip=true -pl org.neo4j:neo4j-cypher -am

WORKDIR /tmp/build/TGraph-demo-test
RUN mvn -B install -DskipTests

ENTRYPOINT /bin/bash
EXPOSE 8438
VOLUME /tmp/tgraph-db
CMD ['mvn', '-B', 'exec:java', '-Dexec.mainClass=run.inner.KernelWriteSocketServer', '-Dexec.args=/tmp/tgraph-db']