name: Docker Image v4.4

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout default branch
      uses: actions/checkout@v4
    
    - name: Set env variable
      run: |
        echo "BUILD_TIME=$(date +'%Y%m%d')" >> $GITHUB_ENV
        echo "COMMIT_SHA_SHORT=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV
        echo ${{env.BUILD_TIME}}
        echo ${{env.COMMIT_SHA_SHORT}}
    
    - name: Login to hub.docker.com
      uses: docker/login-action@v3
      with:
        username: songjinghe
        password: ${{ secrets.dockerhub }}

    # - name: Build and Push Docker Image (neo4j4.4-oraclejdk21-maven)
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     file: docker/neo4j-env.dockerfile
    #     push: true
    #     tags: |
    #       songjinghe/neo4j-env:${{env.COMMIT_SHA_SHORT}}
    #       songjinghe/neo4j-env:${{env.BUILD_TIME}}
    #       songjinghe/neo4j-env:4.4-latest

    # - name: Build and Push Docker Image (tgraph4.4-maven-cache)
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     file: docker/tgraph-cache-4.4.dockerfile
    #     push: true
    #     tags: |
    #       songjinghe/tgraph-maven-cache:4.4-${{env.COMMIT_SHA_SHORT}}
    #       songjinghe/tgraph-maven-cache:4.4-${{env.BUILD_TIME}}
    #       songjinghe/tgraph-maven-cache:4.4-latest
    
    - name: Build and Push Docker Image (tgraph4.4-demo-test)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: docker/tgraph-demo-test-4.4.dockerfile
        push: true
        tags: |
          songjinghe/tgraph-demo-test:4.4-${{env.COMMIT_SHA_SHORT}}
          songjinghe/tgraph-demo-test:4.4-latest

