name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file docker/ubuntu-oraclejdk-maven.dockerfile --tag ubuntu-oraclejdk-maven:$(date +%s)
    - uses: docker/login-action@v3
      with:
        username: songjinghe
        password: ${{ secrets.dockerhub }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .                # Dockerfile 所在目录
        file: docker/ubuntu-oraclejdk-maven.dockerfile        # Dockerfile 路径（如果不在根目录需修改）
        push: true                # 构建后自动推送
        tags: songjinghe/ubuntu-oraclejdk8-maven:latest
            
